#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')

# flake8 check
flake8 $files
if [ $? -ne 0 ]; then
    echo "flake8 errors found. Commit blocked."
    exit 1
fi

# secret check
if grep -rE "(password|api_key|SECRET_KEY)" $files; then
    echo "Bhai kya kar raha hai, secret/API key commit mat kar 😭"
    exit 1
fi

exit 0